#build
FROM node:14.15.4-alpine3.12 as build

USER node

RUN mkdir -p /home/node/app

WORKDIR /home/node/app

COPY --chown=node package*.json ./

COPY --chown=node ./ .

RUN npm run build

EXPOSE 3001

CMD ["npm", "run", "start"]
