apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - port: 8000 # porta de acesso externo
    targetPort: 3001 # porta dos pods
